### ISSUE TITLE
The crates.io version is incorrect

### ISSUE THREAD

**Issue by kevinaboos** [valarauca/amd64_timer#1]
The version of this on crates.io is wrong, but the repository is correct. It seems like you may have forgotten to push it to crates.io? 

Specifically, the line `((mask&high)<<32) | (mask&low)` is missing the `<<32` bitshifting part, resulting in an incorrect value.

**Comment by valarauca** [comment]
I'll jump on it this evening.

**Comment by valarauca** [comment]
Updated the crate to `v1.2.0` 

The bug should be fixed, also added a richer API to account for a weird platform difference between AMD and Intel, which is minor, but idk.
